# POST http://localhost:3001/login HTTP/1.1
# Content-Type: application/json

# {
#     "username": "piyalak",
#     "password": "11111111"
# }

# GET http://localhost:3001/chatroom HTTP/1.1

# GET http://localhost:3001/chatroom/2

# GET http://localhost:3001/pettype

# POST http://localhost:3001/api/Register/add HTTP/1.1
# Content-Type: application/json

# {
#     "username": "d",
#     "password": "aaaaaaaa" 
# }


# GET http://localhost:3001/hats/1


# POST http://localhost:3001/updateCoins HTTP/1.1
# Content-Type: application/json

# {
#     "hatID": 3,
#     "userID": 2
# }


# GET http://localhost:3001/userCloth/2

# GET http://localhost:3001/cloth/1


# POST http://localhost:3001/updateCoinsCloth HTTP/1.1
# Content-Type: application/json

# {
#     "clothID": 2,
#     "userID": 1
# }

# POST http://localhost:3001/addUserCloth HTTP/1.1
# Content-Type: application/json

# {
#     "clothID": 1,
#     "userID": 1
# }


# GET http://localhost:3001/userHats/1

# POST http://localhost:3001/updateDisplayName HTTP/1.1
# Content-Type: application/json

# {
#     "displayName": "เจ้าขนฟู",
#     "userID": 1
# }

GET http://localhost:3001/hatdetailuser/3
